### ISSUE TITLE
input() text entry blocks are very wide

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/ckeditor-binder-plugin#114] opened 2020-09-29 06:15 UTC
Delmar posted this to the construction forum:

On this new page: https://chem.libretexts.org/Under_Construction/PIB_Jupyter/Part_2%3A_Particle_in_an_Infinite_Potential_Box

The input entries in block 37 are too long horizontally for the screen. Any way to narrow them up (by default or otherwise)?

![wide-block](https://user-images.githubusercontent.com/276007/94520073-ef812680-022b-11eb-95da-4b64299cb412.png)

**Comment by rkevin-arch** [comment] 2020-09-29 09:24
This `width: 100%` is the culprit here.
![image](https://user-images.githubusercontent.com/5837628/94539653-61407c80-01fa-11eb-9041-cd841198fc8b.png)
It's from an [anonymous.css](https://a.mtstatic.com/@cache/layout/anonymous.css?_=31d184144b179e3bfb0b5e2e0ae2ab06_Y2hlbS5saWJyZXRleHRzLm9yZw==:site_4334), which seems to be included in line 1927 in the HTML source. I'm not sure where that code is coming from, so @Miniland1333 might be of more help here. Alternatively, we can hardcode some css to force the box width to be a certain value.

**Comment by Miniland1333** [comment] 2020-09-29 16:57
In this instance, I do not have the capability of modifying this CSS directly as it is the default stylesheet for Mindtouch.

To fix the issue, instead just insert the more specific CSS into the CSS file or code you are loading:
```CSS
.thebelab-widget input {
    width: unset;
}
```
![image](https://user-images.githubusercontent.com/12994749/94589435-1b0b0d80-023a-11eb-84ad-810c034dee7a.png)

**Comment by narrator0** [comment] 2020-09-29 22:01
I can reproduce this page on jupyteLab and see what's the expected CSS and set it to that

**Comment by moorepants** [comment] 2020-10-02 08:28
Delmar just wrote me the "However, it is still there on the page of concern even though the github page says the issue was closed. Am I missing something?" Can you investigate?

**Comment by sandertyu** [comment] 2020-10-02 21:34
Okay, turns out we had simply forgotten to merge the changes onto master. It may take a few minutes (hours?) to deploy onto production. Once someone confirms they see the changes, we'll close this issue.

**Comment by rkevin-arch** [comment] 2020-10-02 22:43
It's definitely fixed now.

**Closed as completed by rkevin-arch** 2020-10-02 22:43 UTC
