### ISSUE TITLE
Cannot update earlier code output with later code cells

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/ckeditor-binder-plugin#107] opened 2020-09-10 06:59 UTC
Using [this notebook](https://staging.jupyter.libretexts.org/user/noasanders/files/ipyleaflet.ipynb?_xsrf=2%7Cd562d34e%7C81654a3241fe36d554f4f1e26fc2435e%7C1599178723) (download link) example with ipyleaflet, on Jupyterhub you can display the map with one cell, add the heatmap with another, and then animate the heatmap in a final cell. This requires the later "updating" cells to communicate with the first cell for it to adjust its output. This sort of behavior is also possible in Thebe, but it does not work at all on Libretexts for any type of code. This is a very useful feature and we should identify potential sources and cures for the error. 

You can see the intended output from Jupyterhub below; 
![ipyleaflet in jupyterhub](https://cdn.discordapp.com/attachments/387895582733369346/753509455739748412/unknown.png)

**Comment by sandertyu** [comment] 2020-09-10 07:07
Using similar code on Libretexts, you can get this output;

![ipyleaflet in libretexts](https://cdn.discordapp.com/attachments/387895582733369346/753510706724208720/unknown.png)

There is no way to get the for loop animation to work currently; putting it into the same cell will just run the for loop and then display the image afterwards, and putting the loop in its own cell runs into the same communication problem that this issue was opened for in the first place. For some reason the heatmap doesn't load at all either, although pasting the same exact code into JupyterLab or even Thebe produces working results. A clue is that when you paste that code into Thebe, the javascript execution refusal error does not appear. Likely something is in conflict on Libretexts and we can investigate further.

**Comment by sandertyu** [comment] 2020-10-28 08:22
We wanted to test if the [HTML structure](https://github.com/LibreTexts/ckeditor-binder-plugin/issues/60) used for the CKEditor plugin was causing issues with updating the code output. You can see the replicated structure below, the one using `numpy` is on LibreTexts and the one with `ipyleaflet` is from a simple HTML page [here](https://github.com/sandertyu/widgetstuffs/blob/master/Thebe/divtest.html).

![LibreTexts](https://cdn.discordapp.com/attachments/763198235237154837/770909954848456714/unknown.png)

![Thebe](https://cdn.discordapp.com/attachments/763198235237154837/770910030530740234/unknown.png)

The full linked code runs perfectly fine on Thebe, and we can display the map, then the heatmap, then the animation. As noted before, this doesn't work on LibreTexts, so we're pretty sure the problem is definitely *not* with the HTML itself. Instead, the issue probably lies with a javascript package conflict, version incompatibility, or design choice.

**Comment by mandeepika** [comment] 2021-03-01 02:20
Update: 

In Thebe, adding heat map in a new cell after the cell which displays the original map works fine as stated before. 

In CKEditor Binder plugin, if you add the map in one cell and then add a new cell for the heat map and try to run it, it does not work. It gives the following error:
![image](https://user-images.githubusercontent.com/67208398/109442591-81fd4000-79ed-11eb-9356-c902477d5f46.png)

However, when a new heatmap cell is added, it works if you rerun the previous cell containing the map, and then run the heatmap cell. It does not display any error and works as expected by adding heat layer to the map:
![image](https://user-images.githubusercontent.com/67208398/109442789-ef10d580-79ed-11eb-878e-6644617075e5.png)

Adding the heatmap to the same cell as the original map works as well:
![image](https://user-images.githubusercontent.com/67208398/109442891-19fb2980-79ee-11eb-832d-a73889144773.png)

**Comment by moorepants** [comment] 2021-03-01 09:12
The `NameError: Heatmap is not defined` occurs because the kernel doesn't think that class has been imported.  This page has imports in a prior cell that work in a later cell:
https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipywidgets_for_Interactivity/Enabling_and_Using_Interactive_Matplotlib_Features

I'm not clear why this example would work and the heatmap one wouldn't.

**Comment by mandeepika** [comment] 2021-03-02 22:24
Running it in the https://query.libretexts.org/Development/Testing, the heatmap does not work still. The cells still cannot communicate for some reason. Even putting it into the same cell does not work.

However, all of this does work in ckeditor binder plugin locally as I mentioned in the comment above.

This is what was written from before [here](https://github.com/LibreTexts/widget-testing#widgets-with-problems-on-libretexts):
`These widgets work properly in Thebe but not so well on Libretexts due to limitations of the CKEditor Binder Plugin. Cells cannot retroactively change the output of another cell in CKEditor Binder Plugin, so these widgets are severely limited.`

So that means the issue is not the ckeditor anymore right?

**Comment by sandertyu** [comment] 2021-03-03 00:32
I believe so, I'm able to get all the cells to work perfectly fine, even getting the animation running in local development CKEditor Binder Plugin;

![binder-plugin](https://cdn.discordapp.com/attachments/763198235237154837/816467321077104681/unknown.png)

**Comment by moorepants** [comment] 2021-03-03 07:07
So, it works in ckeditor+thebe locally, but not on libretexts?

We should inspect the HTML that is actually generated on libretexts for any anomalies and then also check the console.

**Comment by mandeepika** [comment] 2021-03-03 07:18
> So, it works in ckeditor+thebe locally, but not on libretexts?

Yes, exactly.

**Comment by mandeepika** [comment] 2021-03-05 21:14
(Putting all the errors here that I get in the web console when trying to run ipyleaflet code cells on [https://query.libretexts.org/Development/Testing](https://query.libretexts.org/Development/Testing)).

This is what I get before running any cell:
![image](https://user-images.githubusercontent.com/67208398/110173493-86da3f00-7db3-11eb-9b93-da1b940fcc9b.png)

After I run the first cell which only contains the map:
![image](https://user-images.githubusercontent.com/67208398/110173697-d6b90600-7db3-11eb-9e09-ecfbb2a8ce2c.png)

Right after that when I run the the cell containing the heatmap, there is no change in the web console at all:
![image](https://user-images.githubusercontent.com/67208398/110173819-09fb9500-7db4-11eb-89d0-ca7cda319428.png)

**Comment by moorepants** [comment] 2021-03-06 06:12
In the first block, you can look for that syntax error. Maybe it is something incorrect in thebe's code.

The 404's on the two things from unpkg should be checked. That may be unrelated to ckeditor/thebe and be something that libretexts fails to load. Find out where those are being loaded from (check html source or and require.js calls).

In the next cells the 404 error from require.js should be investigated. Leaflet is using require.js to try to load some js library(ies) and is failing.

**Comment by moorepants** [comment] 2021-03-06 06:14
I think we've had trouble with require.js before on the site, but can't remember the details. You can search github.com/libretexts for any clues.

**Comment by moorepants** [comment] 2021-03-06 06:20
I got this error on query:
```
The resource from “https://query.libretexts.org/Sandboxes/jupyter-leaflet.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by moorepants** [comment] 2021-03-06 06:23
My error may not be an issue, I guess ipyleaflet may look for a local copy of the js lib first, then grab from unpkg as a fall back.

**Comment by moorepants** [comment] 2021-03-06 06:34
I'm not really seeing any relevant JS errors when I run the code in firefox. I think you should reach out to the ipyleaflet developers, maybe they have a chat channel or forum. Give them a link to a page on query with the code so they can run it and inspect things themselves. You could also show that it works in thebe loaded into a basic site (like the thebe examples). Also what Henry's debugging video. He may give some tips to know what are the likely conflicts with things that are on Libretexts.

**Comment by moorepants** [comment] 2021-03-06 06:35
I've been trying this example:

https://ipyleaflet.readthedocs.io/en/latest/api_reference/velocity.html

**Comment by moorepants** [comment] 2021-03-06 06:37
If I load the velocity example and then drag the map (to pan with mouse) I get this error:
```
Could not send widget sync message Error: Cannot send
    send comm.js:132
    send services-shim.js:37
    send_sync_message widget.js:449
    sync widget.js:391
    save Backbone
    save_changes widget.js:471
    touch widget.js:620
    leaflet_events Map.js:265
    promise callback*leaflet_events/< Map.js:264
    fire leaflet-src.js:588
    setTimeout handler*invalidateSize leaflet-src.js:3566
    _resizeRequest leaflet-src.js:4305
    k leaflet-src.js:241
    _onResize leaflet-src.js:4304
    s leaflet-src.js:2669
    Ee leaflet-src.js:2696
    ke leaflet-src.js:2611
    _initEvents leaflet-src.js:4294
    initialize leaflet-src.js:3105
    n leaflet-src.js:296
    map leaflet-src.js:4691
    create_obj Map.js:252
    promise callback*create_obj Map.js:245
    render_leaflet Map.js:231
    promise callback*render Map.js:227
    state_change manager-base.js:93
    promise callback*S</e.prototype.create_view/e.state_change< manager-base.js:87
    promise callback*S</e.prototype.create_view manager-base.js:86
    display_model manager-base.js:73
    renderModel output_renderers.js:18
    createRenderedMimetype widget.js:435
    createOutputItem widget.js:407
    _insertOutput widget.js:390
    onModelChanged widget.js:218
    u index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    _onListChanged model.js:231
    u index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    push observablelist.js:135
    _add model.js:207
    add model.js:128
    _onIOPub widget.js:92
    _handleIOPub future.js:229
    handleMsg future.js:199
    _handleMessage default.js:1119
    _msgChain default.js:108
    promise callback*g/this._onWSMessage default.js:105
    _createSocket default.js:74
    g default.js:166
    connectTo manager.js:108
    startNew manager.js:154
    requestKernel thebelab.js:398
    promise callback*requestKernel thebelab.js:397
    requestBinderKernel thebelab.js:416
```

**Comment by moorepants** [comment] 2021-03-06 06:46
I wonder if the canvas layer is just not displaying. I see this in the DOM for the velocity example:
```
<canvas class="leaflet-layer leaflet-zoom-animated velocity-overlay" width="1272" height="400" style="transform: translate3d(0px, 0px, 0px);"></canvas>
```
That is the layer that shows the animated arrows. It is there, but it isn't displaying.

**Comment by moorepants** [comment] 2021-03-06 06:53
@Miniland1333 I have an example here; https://query.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu

After you run it there is this in the DOM:

```
<div class="leaflet-pane leaflet-overlay-pane"><canvas class="leaflet-layer leaflet-zoom-animated velocity-overlay" width="1272" height="400" style="transform: translate3d(0px, 0px, 0px);"></canvas></div>
```

But it doesn't display. It does on other websites. I'm not seeing might cause that. Do you have an clues?

**Comment by Miniland1333** [comment] 2021-03-06 21:13
![image](https://user-images.githubusercontent.com/12994749/110220829-28799300-7e7d-11eb-981f-f1da8edeaa2b.png)

It looks like the following CSS rule is the issue:
```CSS
canvas, img, object, video {
    max-width: 100%;
}
```
The solution would either be to add a more specific CSS rule to override this generic one or to give the parent <div> a width for the <canvas> to stretch to.

Also, I must say that this is a lovely example to watch animate.

**Comment by moorepants** [comment] 2021-03-06 21:39
Nice! So maybe this issue is that our container isn't setting widths properly (or at least not like jupyter lab or default thebe).

**Comment by mandeepika** [comment] 2021-03-08 07:44
> The 404's on the two things from unpkg should be checked. That may be unrelated to ckeditor/thebe and be something that libretexts fails to load. Find out where those are being loaded from (check html source or and require.js calls).

So, when running the ipyleaflet code cells in ckeditor locally, I get the same 404 error:

![image](https://user-images.githubusercontent.com/67208398/110287784-ed21b600-7f9b-11eb-853a-c75eb41dc4fc.png)

This is the same error that I was getting on [https://query.libretexts.org/Development/Testing](https://query.libretexts.org/Development/Testing) when loading jupyter-leaflet.js. I was trying to look at the request call stack and the require.min.js gives an error at the same place on both query.libretexts.org and ckeditor locally:

![image](https://user-images.githubusercontent.com/67208398/110288768-5bb34380-7f9d-11eb-8d41-5e34c49baec3.png)

![image](https://user-images.githubusercontent.com/67208398/110288829-6b328c80-7f9d-11eb-921b-1c1d12742f5a.png)

So, this error does not prevent the animation from displaying on ckeditor. (So, I am assuming this error might not be the issue for animation on libretexts as well!? Not v sure)

**Comment by moorepants** [comment] 2021-03-08 08:31
Yes, the errors are not the problem. @Miniland1333 showed that the issue is a css issue. There is conflicting css that prevents the canvas element from being displayed.

**Comment by TimStewartJ** [comment] 2021-03-10 20:30
I've added a css rule that should fix this issue in the ipyleaflet-fix branch and deployed it to query.libretexts.org. The fix should now be visible at https://query.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu. I'm unsure if this impacts anything else so other widgets and stuff should be tested. The only thing I did was add 
```
.thebelab-cell canvas {
  max-width: unset;
}
```
to `plugin.scss`.

**Comment by moorepants** [comment] 2021-03-10 20:37
Nice!

It'd be worth at least testing the other packages we know work, ipympl, volume, etc, to make sure they don't have a canvas and rely on that max width. Or find out if that max width is set by libretext, if so unsetting it inside the thebelab cells should be fine.

**Comment by TimStewartJ** [comment] 2021-08-18 18:03
I'll go ahead and close this issue consider it has been resolved for a while now.

**Closed as completed by TimStewartJ** 2021-08-18 18:03 UTC
